-- Preserve input rows and exact Decimal values; financial policy belongs upstream.
select
    r.cik,
    r.accession_number,
    r.metric_code,
    r.form,
    r.filing_date,
    r.report_date,
    r.fiscal_year_focus,
    r.fiscal_period_focus,
    r.period_kind,
    r.period_start,
    r.period_end,
    r.period_instant,
    r.period_classification as period_label,
    'reported'::varchar as value_origin,
    r.value_decimal,
    r.unit_expression,
    r.selection_rule_version,
    r.period_rule_version,
    null::varchar as derivation_rule_version,
    null::varchar as derivation_method,
    r.concept_namespace,
    r.concept_local_name,
    r.raw_value,
    r.source_occurrence_id as current_source_occurrence_id,
    r.source_document_name as current_source_document_name,
    r.source_sha256 as current_source_sha256,
    r.value_decimal as current_value_decimal,
    r.supporting_occurrence_ids as current_supporting_occurrence_ids,
    null::varchar as previous_accession_number,
    null::varchar as previous_source_occurrence_id,
    null::varchar as previous_source_document_name,
    null::varchar as previous_source_sha256,
    null::decimal(38,18) as previous_value_decimal,
    []::varchar[] as previous_supporting_occurrence_ids,
    null::date as cumulative_period_start,
    null::date as previous_period_end,
    r.decimals as current_decimals,
    r.precision as current_precision,
    null::varchar as previous_decimals,
    null::varchar as previous_precision
from {{ ref('int_reported_financial_periods') }} as r
where r.period_classification in ('annual', 'quarter', 'year_to_date', 'instant')
union all
select
    d.cik,
    d.accession_number,
    d.metric_code,
    d.form,
    d.filing_date,
    d.report_date,
    d.fiscal_year_focus,
    d.fiscal_period_focus,
    d.period_kind,
    d.period_start,
    d.period_end,
    d.period_instant,
    d.period_label,
    d.value_origin,
    d.value_decimal,
    d.unit_expression,
    null::varchar as selection_rule_version,
    null::varchar as period_rule_version,
    d.derivation_rule_version,
    d.derivation_method,
    null::varchar as concept_namespace,
    null::varchar as concept_local_name,
    null::varchar as raw_value,
    d.current_source_occurrence_id,
    d.current_source_document_name,
    d.current_source_sha256,
    d.current_value_decimal,
    d.current_supporting_occurrence_ids,
    d.previous_accession_number,
    d.previous_source_occurrence_id,
    d.previous_source_document_name,
    d.previous_source_sha256,
    d.previous_value_decimal,
    d.previous_supporting_occurrence_ids,
    d.cumulative_period_start,
    d.previous_period_end,
    d.current_decimals,
    d.current_precision,
    d.previous_decimals,
    d.previous_precision
from {{ ref('int_derived_quarterly_cash_flow') }} as d
union all
select
    d.cik,
    d.accession_number,
    d.metric_code,
    d.form,
    d.filing_date,
    d.report_date,
    d.fiscal_year_focus,
    d.fiscal_period_focus,
    d.period_kind,
    d.period_start,
    d.period_end,
    d.period_instant,
    d.period_label,
    d.value_origin,
    d.value_decimal,
    d.unit_expression,
    null::varchar as selection_rule_version,
    null::varchar as period_rule_version,
    d.derivation_rule_version,
    d.derivation_method,
    null::varchar as concept_namespace,
    null::varchar as concept_local_name,
    null::varchar as raw_value,
    d.current_source_occurrence_id,
    d.current_source_document_name,
    d.current_source_sha256,
    d.current_value_decimal,
    d.current_supporting_occurrence_ids,
    d.previous_accession_number,
    d.previous_source_occurrence_id,
    d.previous_source_document_name,
    d.previous_source_sha256,
    d.previous_value_decimal,
    d.previous_supporting_occurrence_ids,
    d.cumulative_period_start,
    d.previous_period_end,
    d.current_decimals,
    d.current_precision,
    d.previous_decimals,
    d.previous_precision
from {{ ref('int_derived_q4_financial_metrics') }} as d
